[package]
name = "ankimd"
version = "0.1.0"
authors = ["Niko Linnansalo <niko@linnansalo.com>"]
edition = "2018"

[lib]
name = "anki_csv"
path = "src/anki_csv.rs"

[[bin]]
name = "ankimd"
path = "src/main.rs"

[dependencies]
regex = "1"
csv = "1"
comrak = "0.7"
clap = "3.0.0-beta.1"
chrono = "0.4"
