[package]
name = "ankimd"
version = "0.1.0"
authors = ["Niko Linnansalo <niko@linnansalo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
csv = "1"
comrak = "0.7"
clap = "3.0.0-beta.1"
